apiVersion: v1
kind: Namespace
metadata:
  name: codeinterpreter
  labels:
    app.kubernetes.io/part-of: code-interpreter
---
apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
  labels:
    app.kubernetes.io/part-of: code-interpreter
    isolation: strict
