# =============================================================================
# Infrastructure Deployment Script (PowerShell Native)
# Deploys all Azure resources using Bicep
# =============================================================================
param(
    [string]$ResourceGroup = $(if ($env:RESOURCE_GROUP) { $env:RESOURCE_GROUP } else { "rg-code-interpreter" }),
    [string]$PrimaryLocation = $(if ($env:PRIMARY_LOCATION) { $env:PRIMARY_LOCATION } else { "indonesiacentral" }),
    [string]$OpenAiLocation = $(if ($env:OPENAI_LOCATION) { $env:OPENAI_LOCATION } else { "southeastasia" }),
    [string]$Environment = $(if ($env:ENVIRONMENT) { $env:ENVIRONMENT } else { "dev" }),
    [string]$BaseName = $(if ($env:BASE_NAME) { $env:BASE_NAME } else { "codeinterp" }),
    # Existing Azure OpenAI — set these to skip creating a new resource
    [string]$ExistingOpenAiEndpoint = $(if ($env:AZURE_OPENAI_ENDPOINT) { $env:AZURE_OPENAI_ENDPOINT } else { "" }),
    [string]$ExistingOpenAiDeployment = $(if ($env:AZURE_OPENAI_DEPLOYMENT) { $env:AZURE_OPENAI_DEPLOYMENT } else { "" }),
    [string]$ExistingOpenAiKey = $(if ($env:AZURE_OPENAI_KEY) { $env:AZURE_OPENAI_KEY } else { "" })
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

$useExistingOpenAi = $ExistingOpenAiEndpoint -ne ""

Write-Host "=============================================" -ForegroundColor Cyan
Write-Host "  Code Interpreter - Infrastructure Deploy"    -ForegroundColor Cyan
Write-Host "=============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Resource Group:   $ResourceGroup"
Write-Host "  Primary Location: $PrimaryLocation"
Write-Host "  Environment:      $Environment"
if ($useExistingOpenAi) {
    Write-Host "  OpenAI:           EXISTING ($ExistingOpenAiEndpoint)" -ForegroundColor Green
} else {
    Write-Host "  OpenAI:           NEW (will create in $OpenAiLocation)"
}
Write-Host ""

# Step 1: Create Resource Group
Write-Host "[1/4] Creating resource group..." -ForegroundColor Yellow
az group create `
    --name $ResourceGroup `
    --location $PrimaryLocation `
    --tags project=code-interpreter environment=$Environment `
    --output none
Write-Host "  Resource group '$ResourceGroup' ready."

# Step 2: Deploy Bicep
Write-Host "[2/4] Deploying infrastructure (Bicep)..." -ForegroundColor Yellow
Write-Host "  This may take 10-15 minutes..."

$bicepParams = @(
    "baseName=$BaseName",
    "primaryLocation=$PrimaryLocation",
    "openAiLocation=$OpenAiLocation",
    "environment=$Environment"
)
if ($useExistingOpenAi) {
    $bicepParams += "existingOpenAiEndpoint=$ExistingOpenAiEndpoint"
    $bicepParams += "existingOpenAiDeploymentName=$ExistingOpenAiDeployment"
}

$deployOutput = az deployment group create `
    --resource-group $ResourceGroup `
    --template-file "$ProjectRoot\infra\main.bicep" `
    --parameters @bicepParams `
    --output json | ConvertFrom-Json

if ($LASTEXITCODE -ne 0) {
    Write-Host "Bicep deployment FAILED." -ForegroundColor Red
    exit 1
}

# Extract outputs
$outputs = $deployOutput.properties.outputs
$aksClusterName = $outputs.aksClusterName.value
$acrLoginServer = $outputs.acrLoginServer.value
$acrName = $outputs.acrName.value
$storageAccountName = $outputs.storageAccountName.value
$storageBlobEndpoint = $outputs.storageBlobEndpoint.value
$openAiEndpoint = $outputs.openAiEndpoint.value
$openAiDeploymentName = $outputs.openAiDeploymentName.value

Write-Host "  Infrastructure deployed successfully." -ForegroundColor Green
Write-Host ""
Write-Host "  AKS Cluster:    $aksClusterName"
Write-Host "  ACR:            $acrLoginServer"
Write-Host "  Storage:        $storageAccountName"
Write-Host "  OpenAI:         $openAiEndpoint"
Write-Host ""

# Step 3: Get AKS credentials
Write-Host "[3/4] Getting AKS credentials..." -ForegroundColor Yellow
az aks get-credentials `
    --resource-group $ResourceGroup `
    --name $aksClusterName `
    --overwrite-existing `
    --output none
Write-Host "  kubectl configured for cluster '$aksClusterName'."

# Step 4: Install NGINX Ingress Controller
Write-Host "[4/4] Installing NGINX Ingress Controller..." -ForegroundColor Yellow
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0/deploy/static/provider/cloud/deploy.yaml 2>$null
Write-Host "  NGINX Ingress Controller installed."

# Save outputs for app deployment script
$outputsFile = Join-Path $ProjectRoot ".env.infra.ps1"
$openAiCreated = $outputs.openAiCreated.value
@"
# Auto-generated by deploy-infra.ps1 - $(Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
`$script:ResourceGroup = "$ResourceGroup"
`$script:AksClusterName = "$aksClusterName"
`$script:AcrLoginServer = "$acrLoginServer"
`$script:AcrName = "$acrName"
`$script:StorageAccountName = "$storageAccountName"
`$script:StorageBlobEndpoint = "$storageBlobEndpoint"
`$script:OpenAiEndpoint = "$openAiEndpoint"
`$script:OpenAiDeploymentName = "$openAiDeploymentName"
`$script:OpenAiCreated = `$$openAiCreated
`$script:ExistingOpenAiKey = "$ExistingOpenAiKey"
"@ | Set-Content -Path $outputsFile -Encoding UTF8

Write-Host ""
Write-Host "=============================================" -ForegroundColor Green
Write-Host "  Infrastructure deployment complete!"          -ForegroundColor Green
Write-Host "  Outputs saved to: $outputsFile"
Write-Host "  Next: run scripts\deploy-apps.ps1"
Write-Host "=============================================" -ForegroundColor Green
