#!/bin/bash
# =============================================================================
# Infrastructure Deployment Script
# Deploys all Azure resources using Bicep
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Configuration — override via environment variables
RESOURCE_GROUP="${RESOURCE_GROUP:-rg-code-interpreter}"
PRIMARY_LOCATION="${PRIMARY_LOCATION:-indonesiacentral}"
OPENAI_LOCATION="${OPENAI_LOCATION:-southeastasia}"
ENVIRONMENT="${ENVIRONMENT:-dev}"
BASE_NAME="${BASE_NAME:-codeinterp}"

echo "============================================="
echo "  Code Interpreter — Infrastructure Deploy"
echo "============================================="
echo ""
echo "  Resource Group:   ${RESOURCE_GROUP}"
echo "  Primary Location: ${PRIMARY_LOCATION}"
echo "  OpenAI Location:  ${OPENAI_LOCATION}"
echo "  Environment:      ${ENVIRONMENT}"
echo ""

# Step 1: Create Resource Group
echo "[1/4] Creating resource group..."
az group create \
    --name "${RESOURCE_GROUP}" \
    --location "${PRIMARY_LOCATION}" \
    --tags project=code-interpreter environment="${ENVIRONMENT}" \
    --output none
echo "  Resource group '${RESOURCE_GROUP}' ready."

# Step 2: Deploy Bicep
echo "[2/4] Deploying infrastructure (Bicep)..."
echo "  This may take 10-15 minutes..."

DEPLOYMENT_OUTPUT=$(az deployment group create \
    --resource-group "${RESOURCE_GROUP}" \
    --template-file "${PROJECT_ROOT}/infra/main.bicep" \
    --parameters baseName="${BASE_NAME}" \
                 primaryLocation="${PRIMARY_LOCATION}" \
                 openAiLocation="${OPENAI_LOCATION}" \
                 environment="${ENVIRONMENT}" \
    --output json)

# Extract outputs
AKS_CLUSTER_NAME=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.aksClusterName.value')
ACR_LOGIN_SERVER=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.acrLoginServer.value')
ACR_NAME=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.acrName.value')
STORAGE_ACCOUNT_NAME=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.storageAccountName.value')
STORAGE_BLOB_ENDPOINT=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.storageBlobEndpoint.value')
OPENAI_ENDPOINT=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.openAiEndpoint.value')
OPENAI_DEPLOYMENT_NAME=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.openAiDeploymentName.value')

echo "  Infrastructure deployed successfully."
echo ""
echo "  AKS Cluster:    ${AKS_CLUSTER_NAME}"
echo "  ACR:            ${ACR_LOGIN_SERVER}"
echo "  Storage:        ${STORAGE_ACCOUNT_NAME}"
echo "  OpenAI:         ${OPENAI_ENDPOINT}"
echo ""

# Step 3: Get AKS credentials
echo "[3/4] Getting AKS credentials..."
az aks get-credentials \
    --resource-group "${RESOURCE_GROUP}" \
    --name "${AKS_CLUSTER_NAME}" \
    --overwrite-existing \
    --output none
echo "  kubectl configured for cluster '${AKS_CLUSTER_NAME}'."

# Step 4: Install NGINX Ingress Controller
echo "[4/4] Installing NGINX Ingress Controller..."
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0/deploy/static/provider/cloud/deploy.yaml 2>/dev/null || true
echo "  NGINX Ingress Controller installed."

# Save outputs for app deployment script
OUTPUTS_FILE="${PROJECT_ROOT}/.env.infra"
cat > "${OUTPUTS_FILE}" <<EOF
# Auto-generated by deploy-infra.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
RESOURCE_GROUP=${RESOURCE_GROUP}
AKS_CLUSTER_NAME=${AKS_CLUSTER_NAME}
ACR_LOGIN_SERVER=${ACR_LOGIN_SERVER}
ACR_NAME=${ACR_NAME}
STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
STORAGE_BLOB_ENDPOINT=${STORAGE_BLOB_ENDPOINT}
OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
OPENAI_DEPLOYMENT_NAME=${OPENAI_DEPLOYMENT_NAME}
EOF

echo ""
echo "============================================="
echo "  Infrastructure deployment complete!"
echo "  Outputs saved to: ${OUTPUTS_FILE}"
echo "  Next: run scripts/deploy-apps.sh"
echo "============================================="
